version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"