[package]
name = "fission"
authors = ["James Walker <walkah@walkah.net>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
base64 = "0.13.0"
clap = { version = "3.2.12", features = ["derive"] }
ed25519-zebra = "3.0.0"